export const All_PRODUCTS_REQUEST="All_PRODUCTS_REQUEST"
export const All_PRODUCTS_SUCCESS ="All_PRODUCTS_SUCCESS"
export const All_PRODUCTS_FAIL = "ALL PRODUCTS_FAIL"

export const CLEAR_ERRORS = "CLEAR ERRORS"

export const PRODUCT_DETAIL_REQUEST='PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL= "PRODUCT_DETAIL_FAIL"